
name: Java Maven Build & Publish Artifact

on:
 push:
   branches:
     - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Setup JDK 17
     uses: actions/setup-java@v3
     with:
       java-version: '11'
   - name: Build with Maven
     run: mvn clean package
   - name: Run unit tests
     run: mvn test
   - name: Run static code analysis (CheckStyle, PMD)
     run: |
       mvn checkstyle:check pmd:check
